version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: inclusive_postgres
    restart: always
    environment:
      POSTGRES_DB: auth_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: inclusive_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@inclusive.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  pgdata:
